/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed-dim': '#4edea3',
        'on-error': '#ffffff',
        'on-primary': '#ffffff',
        'primary-container': '#2563eb',
        'inverse-surface': '#2d3133',
        'surface-container': '#eceef0',
        'on-tertiary': '#ffffff',
        outline: '#737686',
        'on-primary-fixed': '#00174b',
        'on-secondary-fixed': '#0b1c30',
        'secondary-container': '#d0e1fb',
        error: '#ba1a1a',
        background: '#f7f9fb',
        'tertiary-container': '#007d55',
        'on-tertiary-fixed-variant': '#005236',
        secondary: '#505f76',
        'on-tertiary-fixed': '#002113',
        'surface-bright': '#f7f9fb',
        'on-secondary-fixed-variant': '#38485d',
        primary: '#004ac6',
        'on-surface-variant': '#434655',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#54647a',
        'secondary-fixed': '#d3e4fe',
        'primary-fixed': '#dbe1ff',
        'tertiary-fixed': '#6ffbbe',
        'on-primary-fixed-variant': '#003ea8',
        'surface-container-high': '#e6e8ea',
        'secondary-fixed-dim': '#b7c8e1',
        'surface-tint': '#0053db',
        'primary-fixed-dim': '#b4c5ff',
        tertiary: '#006242',
        'inverse-primary': '#b4c5ff',
        surface: '#f7f9fb',
        'on-primary-container': '#eeefff',
        'on-surface': '#191c1e',
        'error-container': '#ffdad6',
        'surface-container-highest': '#e0e3e5',
        'on-background': '#191c1e',
        'surface-dim': '#d8dadc',
        'outline-variant': '#c3c6d7',
        'surface-variant': '#e0e3e5',
        'surface-container-low': '#f2f4f6',
        'inverse-on-surface': '#eff1f3',
        'on-tertiary-container': '#bdffdb',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        baseline: '4px',
        'sidebar-width': '210px',
        'header-height': '48px',
        'card-padding': '20px',
        'sidebar-collapsed': '54px',
      },
      fontFamily: {
        'body-sm': ['Inter'],
        'headline-lg': ['Inter'],
        'technical-mono': ['JetBrains Mono'],
        'label-caps': ['Inter'],
        'headline-md': ['Inter'],
        'body-lg': ['Inter'],
        'label-bold': ['Inter'],
      },
      fontSize: {
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'technical-mono': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'headline-md': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '20px', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
