// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: apps/api/rpc/pb/shortlink.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShortLinkReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongUrl       string                 `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ApiKey        string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortLinkReq) Reset() {
	*x = CreateShortLinkReq{}
	mi := &file_apps_api_rpc_pb_shortlink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkReq) ProtoMessage() {}

func (x *CreateShortLinkReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_api_rpc_pb_shortlink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkReq.ProtoReflect.Descriptor instead.
func (*CreateShortLinkReq) Descriptor() ([]byte, []int) {
	return file_apps_api_rpc_pb_shortlink_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShortLinkReq) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *CreateShortLinkReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateShortLinkReq) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type CreateShortLinkResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	LongUrl       string                 `protobuf:"bytes,2,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortLinkResp) Reset() {
	*x = CreateShortLinkResp{}
	mi := &file_apps_api_rpc_pb_shortlink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkResp) ProtoMessage() {}

func (x *CreateShortLinkResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_api_rpc_pb_shortlink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkResp.ProtoReflect.Descriptor instead.
func (*CreateShortLinkResp) Descriptor() ([]byte, []int) {
	return file_apps_api_rpc_pb_shortlink_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortLinkResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateShortLinkResp) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

type GetByCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByCodeReq) Reset() {
	*x = GetByCodeReq{}
	mi := &file_apps_api_rpc_pb_shortlink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByCodeReq) ProtoMessage() {}

func (x *GetByCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_api_rpc_pb_shortlink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByCodeReq.ProtoReflect.Descriptor instead.
func (*GetByCodeReq) Descriptor() ([]byte, []int) {
	return file_apps_api_rpc_pb_shortlink_proto_rawDescGZIP(), []int{2}
}

func (x *GetByCodeReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetByCodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	LongUrl       string                 `protobuf:"bytes,2,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	Clicks        int64                  `protobuf:"varint,3,opt,name=clicks,proto3" json:"clicks,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByCodeResp) Reset() {
	*x = GetByCodeResp{}
	mi := &file_apps_api_rpc_pb_shortlink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByCodeResp) ProtoMessage() {}

func (x *GetByCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_api_rpc_pb_shortlink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByCodeResp.ProtoReflect.Descriptor instead.
func (*GetByCodeResp) Descriptor() ([]byte, []int) {
	return file_apps_api_rpc_pb_shortlink_proto_rawDescGZIP(), []int{3}
}

func (x *GetByCodeResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetByCodeResp) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *GetByCodeResp) GetClicks() int64 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *GetByCodeResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type BatchCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongUrls      []string               `protobuf:"bytes,1,rep,name=long_urls,json=longUrls,proto3" json:"long_urls,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateReq) Reset() {
	*x = BatchCreateReq{}
	mi := &file_apps_api_rpc_pb_shortlink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateReq) ProtoMessage() {}

func (x *BatchCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_api_rpc_pb_shortlink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateReq.ProtoReflect.Descriptor instead.
func (*BatchCreateReq) Descriptor() ([]byte, []int) {
	return file_apps_api_rpc_pb_shortlink_proto_rawDescGZIP(), []int{4}
}

func (x *BatchCreateReq) GetLongUrls() []string {
	if x != nil {
		return x.LongUrls
	}
	return nil
}

func (x *BatchCreateReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type BatchCreateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CreateShortLinkResp `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateResp) Reset() {
	*x = BatchCreateResp{}
	mi := &file_apps_api_rpc_pb_shortlink_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateResp) ProtoMessage() {}

func (x *BatchCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_api_rpc_pb_shortlink_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateResp.ProtoReflect.Descriptor instead.
func (*BatchCreateResp) Descriptor() ([]byte, []int) {
	return file_apps_api_rpc_pb_shortlink_proto_rawDescGZIP(), []int{5}
}

func (x *BatchCreateResp) GetItems() []*CreateShortLinkResp {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteShortLinkReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShortLinkReq) Reset() {
	*x = DeleteShortLinkReq{}
	mi := &file_apps_api_rpc_pb_shortlink_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShortLinkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShortLinkReq) ProtoMessage() {}

func (x *DeleteShortLinkReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_api_rpc_pb_shortlink_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShortLinkReq.ProtoReflect.Descriptor instead.
func (*DeleteShortLinkReq) Descriptor() ([]byte, []int) {
	return file_apps_api_rpc_pb_shortlink_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteShortLinkReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DeleteShortLinkReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteShortLinkResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShortLinkResp) Reset() {
	*x = DeleteShortLinkResp{}
	mi := &file_apps_api_rpc_pb_shortlink_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShortLinkResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShortLinkResp) ProtoMessage() {}

func (x *DeleteShortLinkResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_api_rpc_pb_shortlink_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShortLinkResp.ProtoReflect.Descriptor instead.
func (*DeleteShortLinkResp) Descriptor() ([]byte, []int) {
	return file_apps_api_rpc_pb_shortlink_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteShortLinkResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ResolveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveReq) Reset() {
	*x = ResolveReq{}
	mi := &file_apps_api_rpc_pb_shortlink_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveReq) ProtoMessage() {}

func (x *ResolveReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_api_rpc_pb_shortlink_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveReq.ProtoReflect.Descriptor instead.
func (*ResolveReq) Descriptor() ([]byte, []int) {
	return file_apps_api_rpc_pb_shortlink_proto_rawDescGZIP(), []int{8}
}

func (x *ResolveReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ResolveResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongUrl       string                 `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	Blocked       bool                   `protobuf:"varint,2,opt,name=blocked,proto3" json:"blocked,omitempty"` // 命中域名黑名单
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResp) Reset() {
	*x = ResolveResp{}
	mi := &file_apps_api_rpc_pb_shortlink_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResp) ProtoMessage() {}

func (x *ResolveResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_api_rpc_pb_shortlink_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResp.ProtoReflect.Descriptor instead.
func (*ResolveResp) Descriptor() ([]byte, []int) {
	return file_apps_api_rpc_pb_shortlink_proto_rawDescGZIP(), []int{9}
}

func (x *ResolveResp) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *ResolveResp) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

var File_apps_api_rpc_pb_shortlink_proto protoreflect.FileDescriptor

const file_apps_api_rpc_pb_shortlink_proto_rawDesc = "" +
	"\n" +
	"\x1fapps/api/rpc/pb/shortlink.proto\x12\x02pb\"a\n" +
	"\x12CreateShortLinkReq\x12\x19\n" +
	"\blong_url\x18\x01 \x01(\tR\alongUrl\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\"D\n" +
	"\x13CreateShortLinkResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x19\n" +
	"\blong_url\x18\x02 \x01(\tR\alongUrl\"\"\n" +
	"\fGetByCodeReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"n\n" +
	"\rGetByCodeResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x19\n" +
	"\blong_url\x18\x02 \x01(\tR\alongUrl\x12\x16\n" +
	"\x06clicks\x18\x03 \x01(\x03R\x06clicks\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"F\n" +
	"\x0eBatchCreateReq\x12\x1b\n" +
	"\tlong_urls\x18\x01 \x03(\tR\blongUrls\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"@\n" +
	"\x0fBatchCreateResp\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.pb.CreateShortLinkRespR\x05items\"A\n" +
	"\x12DeleteShortLinkReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"%\n" +
	"\x13DeleteShortLinkResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\" \n" +
	"\n" +
	"ResolveReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"B\n" +
	"\vResolveResp\x12\x19\n" +
	"\blong_url\x18\x01 \x01(\tR\alongUrl\x12\x18\n" +
	"\ablocked\x18\x02 \x01(\bR\ablocked2\xa9\x02\n" +
	"\tShortLink\x12B\n" +
	"\x0fCreateShortLink\x12\x16.pb.CreateShortLinkReq\x1a\x17.pb.CreateShortLinkResp\x120\n" +
	"\tGetByCode\x12\x10.pb.GetByCodeReq\x1a\x11.pb.GetByCodeResp\x126\n" +
	"\vBatchCreate\x12\x12.pb.BatchCreateReq\x1a\x13.pb.BatchCreateResp\x12B\n" +
	"\x0fDeleteShortLink\x12\x16.pb.DeleteShortLinkReq\x1a\x17.pb.DeleteShortLinkResp\x12*\n" +
	"\aResolve\x12\x0e.pb.ResolveReq\x1a\x0f.pb.ResolveRespB\x1bZ\x19server/apps/api/rpc/pb;pbb\x06proto3"

var (
	file_apps_api_rpc_pb_shortlink_proto_rawDescOnce sync.Once
	file_apps_api_rpc_pb_shortlink_proto_rawDescData []byte
)

func file_apps_api_rpc_pb_shortlink_proto_rawDescGZIP() []byte {
	file_apps_api_rpc_pb_shortlink_proto_rawDescOnce.Do(func() {
		file_apps_api_rpc_pb_shortlink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_api_rpc_pb_shortlink_proto_rawDesc), len(file_apps_api_rpc_pb_shortlink_proto_rawDesc)))
	})
	return file_apps_api_rpc_pb_shortlink_proto_rawDescData
}

var file_apps_api_rpc_pb_shortlink_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_apps_api_rpc_pb_shortlink_proto_goTypes = []any{
	(*CreateShortLinkReq)(nil),  // 0: pb.CreateShortLinkReq
	(*CreateShortLinkResp)(nil), // 1: pb.CreateShortLinkResp
	(*GetByCodeReq)(nil),        // 2: pb.GetByCodeReq
	(*GetByCodeResp)(nil),       // 3: pb.GetByCodeResp
	(*BatchCreateReq)(nil),      // 4: pb.BatchCreateReq
	(*BatchCreateResp)(nil),     // 5: pb.BatchCreateResp
	(*DeleteShortLinkReq)(nil),  // 6: pb.DeleteShortLinkReq
	(*DeleteShortLinkResp)(nil), // 7: pb.DeleteShortLinkResp
	(*ResolveReq)(nil),          // 8: pb.ResolveReq
	(*ResolveResp)(nil),         // 9: pb.ResolveResp
}
var file_apps_api_rpc_pb_shortlink_proto_depIdxs = []int32{
	1, // 0: pb.BatchCreateResp.items:type_name -> pb.CreateShortLinkResp
	0, // 1: pb.ShortLink.CreateShortLink:input_type -> pb.CreateShortLinkReq
	2, // 2: pb.ShortLink.GetByCode:input_type -> pb.GetByCodeReq
	4, // 3: pb.ShortLink.BatchCreate:input_type -> pb.BatchCreateReq
	6, // 4: pb.ShortLink.DeleteShortLink:input_type -> pb.DeleteShortLinkReq
	8, // 5: pb.ShortLink.Resolve:input_type -> pb.ResolveReq
	1, // 6: pb.ShortLink.CreateShortLink:output_type -> pb.CreateShortLinkResp
	3, // 7: pb.ShortLink.GetByCode:output_type -> pb.GetByCodeResp
	5, // 8: pb.ShortLink.BatchCreate:output_type -> pb.BatchCreateResp
	7, // 9: pb.ShortLink.DeleteShortLink:output_type -> pb.DeleteShortLinkResp
	9, // 10: pb.ShortLink.Resolve:output_type -> pb.ResolveResp
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apps_api_rpc_pb_shortlink_proto_init() }
func file_apps_api_rpc_pb_shortlink_proto_init() {
	if File_apps_api_rpc_pb_shortlink_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_api_rpc_pb_shortlink_proto_rawDesc), len(file_apps_api_rpc_pb_shortlink_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_api_rpc_pb_shortlink_proto_goTypes,
		DependencyIndexes: file_apps_api_rpc_pb_shortlink_proto_depIdxs,
		MessageInfos:      file_apps_api_rpc_pb_shortlink_proto_msgTypes,
	}.Build()
	File_apps_api_rpc_pb_shortlink_proto = out.File
	file_apps_api_rpc_pb_shortlink_proto_goTypes = nil
	file_apps_api_rpc_pb_shortlink_proto_depIdxs = nil
}
