apiVersion: apps/v1
kind: Deployment
metadata:
  name: slink-rpc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: slink-rpc
  template:
    metadata:
      labels:
        app: slink-rpc
    spec:
      containers:
        - name: slink-rpc
          image: slink-server:latest
          args: ["/app/bin/slink-rpc", "-f", "/app/etc/slink.yaml"]
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: slink-rpc
spec:
  selector:
    app: slink-rpc
  ports:
    - port: 8081
      targetPort: 8081
