// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: apps/api/rpc/pb/slink.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	slink_Createslink_FullMethodName = "/pb.slink/Createslink"
	slink_GetByCode_FullMethodName       = "/pb.slink/GetByCode"
	slink_BatchCreate_FullMethodName     = "/pb.slink/BatchCreate"
	slink_Deleteslink_FullMethodName = "/pb.slink/Deleteslink"
	slink_Resolve_FullMethodName         = "/pb.slink/Resolve"
)

// SlinkClient is the client API for slink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// slink 短链核心服务（对内 gRPC，对外不暴露）
type SlinkClient interface {
	Createslink(ctx context.Context, in *CreateslinkReq, opts ...grpc.CallOption) (*CreateslinkResp, error)
	GetByCode(ctx context.Context, in *GetByCodeReq, opts ...grpc.CallOption) (*GetByCodeResp, error)
	BatchCreate(ctx context.Context, in *BatchCreateReq, opts ...grpc.CallOption) (*BatchCreateResp, error)
	Deleteslink(ctx context.Context, in *DeleteslinkReq, opts ...grpc.CallOption) (*DeleteslinkResp, error)
	Resolve(ctx context.Context, in *ResolveReq, opts ...grpc.CallOption) (*ResolveResp, error)
}

type slinkClient struct {
	cc grpc.ClientConnInterface
}

func NewslinkClient(cc grpc.ClientConnInterface) SlinkClient {
	return &slinkClient{cc}
}

func (c *slinkClient) Createslink(ctx context.Context, in *CreateslinkReq, opts ...grpc.CallOption) (*CreateslinkResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateslinkResp)
	err := c.cc.Invoke(ctx, slink_Createslink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slinkClient) GetByCode(ctx context.Context, in *GetByCodeReq, opts ...grpc.CallOption) (*GetByCodeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetByCodeResp)
	err := c.cc.Invoke(ctx, slink_GetByCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slinkClient) BatchCreate(ctx context.Context, in *BatchCreateReq, opts ...grpc.CallOption) (*BatchCreateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCreateResp)
	err := c.cc.Invoke(ctx, slink_BatchCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slinkClient) Deleteslink(ctx context.Context, in *DeleteslinkReq, opts ...grpc.CallOption) (*DeleteslinkResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteslinkResp)
	err := c.cc.Invoke(ctx, slink_Deleteslink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slinkClient) Resolve(ctx context.Context, in *ResolveReq, opts ...grpc.CallOption) (*ResolveResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveResp)
	err := c.cc.Invoke(ctx, slink_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// slinkServer is the server API for slink service.
// All implementations must embed UnimplementedslinkServer
// for forward compatibility.
//
// slink 短链核心服务（对内 gRPC，对外不暴露）
type slinkServer interface {
	Createslink(context.Context, *CreateslinkReq) (*CreateslinkResp, error)
	GetByCode(context.Context, *GetByCodeReq) (*GetByCodeResp, error)
	BatchCreate(context.Context, *BatchCreateReq) (*BatchCreateResp, error)
	Deleteslink(context.Context, *DeleteslinkReq) (*DeleteslinkResp, error)
	Resolve(context.Context, *ResolveReq) (*ResolveResp, error)
	mustEmbedUnimplementedslinkServer()
}

// UnimplementedslinkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedslinkServer struct{}

func (UnimplementedslinkServer) Createslink(context.Context, *CreateslinkReq) (*CreateslinkResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Createslink not implemented")
}
func (UnimplementedslinkServer) GetByCode(context.Context, *GetByCodeReq) (*GetByCodeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByCode not implemented")
}
func (UnimplementedslinkServer) BatchCreate(context.Context, *BatchCreateReq) (*BatchCreateResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCreate not implemented")
}
func (UnimplementedslinkServer) Deleteslink(context.Context, *DeleteslinkReq) (*DeleteslinkResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Deleteslink not implemented")
}
func (UnimplementedslinkServer) Resolve(context.Context, *ResolveReq) (*ResolveResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedslinkServer) mustEmbedUnimplementedslinkServer() {}
func (UnimplementedslinkServer) testEmbeddedByValue()                   {}

// UnsafeslinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to slinkServer will
// result in compilation errors.
type UnsafeslinkServer interface {
	mustEmbedUnimplementedslinkServer()
}

func RegisterslinkServer(s grpc.ServiceRegistrar, srv slinkServer) {
	// If the following call panics, it indicates UnimplementedslinkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&slink_ServiceDesc, srv)
}

func _slink_Createslink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateslinkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(slinkServer).Createslink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: slink_Createslink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(slinkServer).Createslink(ctx, req.(*CreateslinkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _slink_GetByCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(slinkServer).GetByCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: slink_GetByCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(slinkServer).GetByCode(ctx, req.(*GetByCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _slink_BatchCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(slinkServer).BatchCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: slink_BatchCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(slinkServer).BatchCreate(ctx, req.(*BatchCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _slink_Deleteslink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteslinkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(slinkServer).Deleteslink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: slink_Deleteslink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(slinkServer).Deleteslink(ctx, req.(*DeleteslinkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _slink_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(slinkServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: slink_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(slinkServer).Resolve(ctx, req.(*ResolveReq))
	}
	return interceptor(ctx, in, info, handler)
}

// slink_ServiceDesc is the grpc.ServiceDesc for slink service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var slink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.slink",
	HandlerType: (*slinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Createslink",
			Handler:    _slink_Createslink_Handler,
		},
		{
			MethodName: "GetByCode",
			Handler:    _slink_GetByCode_Handler,
		},
		{
			MethodName: "BatchCreate",
			Handler:    _slink_BatchCreate_Handler,
		},
		{
			MethodName: "Deleteslink",
			Handler:    _slink_Deleteslink_Handler,
		},
		{
			MethodName: "Resolve",
			Handler:    _slink_Resolve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/api/rpc/pb/slink.proto",
}
