global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'slink-api'
    static_configs:
      - targets: ['slink-api:8888']
  - job_name: 'slink-rpc'
    static_configs:
      - targets: ['slink-rpc:8081']
  - job_name: 'admin-api'
    static_configs:
      - targets: ['admin-api:8889']
